services:
  - type: web
    name: nyayavanni-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    region: singapore
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.x
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
